# -*- coding: utf-8 -*-
"""Sentiment Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UdhJMCjTh6vASPllNbKK7K4U_v8MQPKj

# **Sentiment Analysis**

## **Import Libraries and Load Datasets**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import nltk

plt.style.use('ggplot')

df = pd.read_csv('/content/sample_data/Reviews.csv')

df.head()

df.shape

"""## **Quick EDA**"""

df = df.head(1000)
df.shape

#Plot count of reviews by Stars
scores = df['Score'].value_counts().sort_index()
colors = plt.cm.viridis(np.linspace(0, 1, len(scores)))
scores.plot(kind='bar',title='Count of Reviews by Stars',
              color=colors,
              figsize=(6,3))

plt.xlabel('Review Stars')
plt.ylabel('Frequency')
plt.show()

"""## **Basic NLP**"""

example = df['Text'][50]
example

from nltk import word_tokenize
nltk.download('punkt_tab')
tokens = word_tokenize(example)
tokens[:10]

nltk.download('averaged_perceptron_tagger_eng')

tagged = nltk.pos_tag(tokens)
tagged[:10]

nltk.download('maxent_ne_chunker_tab')
nltk.download('words')

entities = nltk.chunk.ne_chunk(tagged)
entities.pprint()

nltk.download('vader_lexicon')

from nltk.sentiment import SentimentIntensityAnalyzer
from tqdm.notebook import tqdm

sia = SentimentIntensityAnalyzer()

sia.polarity_scores(example)

res={}
for i, row in tqdm(df.iterrows(), total=len(df)):
  text = row['Text']
  myid = row['Id']
  res[myid] = sia.polarity_scores(text)

vaders = pd.DataFrame(res).T
vaders = vaders.reset_index().rename(columns = {'index':'Id'})
vaders = vaders.merge(df, how='left')
vaders.head(2)

# Plot Score Vs Compound Scores plot
colors = plt.cm.autumn(np.linspace(0, 1, len(scores)))
colors = colors.tolist()
ax = sns.barplot(data=vaders, x='Score', y='compound', palette=colors, hue='Score', legend = False)
ax.set_title('Compound Score by Amazon Star Review')
plt.show()

#Plot graph of Positive, Negative, Neutral
fig, axs = plt.subplots(1, 3, figsize=(12, 3))
sns.barplot(data=vaders, x='Score', y='pos', ax=axs[0], color='Green')
sns.barplot(data=vaders, x='Score', y='neu', ax=axs[1], color='yellow')
sns.barplot(data=vaders, x='Score', y='neg', ax=axs[2], color='Red')
axs[0].set_title('Positive Reviews')
axs[1].set_title('Neutral Reviews')
axs[2].set_title('Negative Reviews')
plt.tight_layout()
plt.show()

"""## **Roberta Pretrained Model**"""

from transformers import AutoTokenizer
from transformers import AutoModelForSequenceClassification
from scipy.special import softmax

MODEL = f"cardiffnlp/twitter-roberta-base-sentiment"
tokenizer = AutoTokenizer.from_pretrained(MODEL)
model = AutoModelForSequenceClassification.from_pretrained(MODEL)

encoded_text = tokenizer(example, return_tensors='pt')
output = model(**encoded_text)
scores = output[0][0].detach().numpy()
scores = softmax(scores)
scores_dict = {
    'roberta_neg' : float(scores[0]),
    'roberta_neu' : float(scores[1]),
    'roberta_pos' : float(scores[2])
}
print(scores_dict)

sia.polarity_scores(example)

def polarity_scores_roberta(example):
    encoded_text = tokenizer(example, return_tensors='pt')
    output = model(**encoded_text)
    scores = output[0][0].detach().numpy()
    scores = softmax(scores)
    scores_dict = {
        'roberta_neg' : float(scores[0]),
        'roberta_neu' : float(scores[1]),
        'roberta_pos' : float(scores[2])
    }
    return scores_dict

res = {}
for i, row in tqdm(df.iterrows(), total=len(df)):
    try:
        text = row['Text']
        myid = row['Id']
        vader_result = sia.polarity_scores(text)
        vader_result_rename = {}
        for key, value in vader_result.items():
            vader_result_rename[f"vader_{key}"] = value
        roberta_result = polarity_scores_roberta(text)
        both = {**vader_result_rename, **roberta_result}
        res[myid] = both
    except RuntimeError:
        print(f'Broke for id {myid}')

results_df = pd.DataFrame(res).T
results_df = results_df.reset_index().rename(columns={'index': 'Id'})
results_df = results_df.merge(df, how='left')

results_df.columns

results_df.head()

"""## **Combine and compare**"""

sns.pairplot(data=results_df,
             vars=['vader_neg', 'vader_neu', 'vader_pos',
                  'roberta_neg', 'roberta_neu', 'roberta_pos'],
            hue='Score',
            palette='tab10',
            height=1.5,
            aspect=1.5)
plt.show()

"""## **Review Examples**"""

results_df.query('Score == 1') \
    .sort_values('roberta_pos', ascending=False)['Text'].values[0:9]

results_df.query('Score == 1') \
    .sort_values('vader_pos', ascending=False)['Text'].values[0]

results_df.query('Score == 5')\
  .sort_values('roberta_neg', ascending=False)['Text'].values[0]

results_df.query('Score == 5')\
  .sort_values('vader_neg', ascending=False)['Text'].values[0]

"""## **The Transformers Pipeline**"""

from transformers import pipeline

sent_pipeline = pipeline("sentiment-analysis")

sent_pipeline('I love sentiment analysis!')

sent_pipeline(example)

pipeline_res = {}
for i, row in tqdm(df.iterrows(), total=len(df)):
  try:
    text = row['Text']
    id = row['Id']
    pipeline_res[id] = sent_pipeline(text)
  except RuntimeError:
    print(f'Escape for id {id}')

final_df = pd.DataFrame({"Id": list(pipeline_res.keys()),
                         "Pipeline Result": [pipeline_res[k][0][f"label"] for k in pipeline_res]})

final_df = final_df.merge(results_df, on="Id", how="right")

final_df.head()

final_df['Pipeline Result'].value_counts()